[package]
name = "hsl"
version = "0.0.1"
edition = "2024"

[dependencies]
name-variant = "0.1.0"
owo-colors = "4.2.3"
dashmap = "7.0.0-rc2"
int-enum = "1.2.0"
clap = { version = "4.5.54", features = ["derive"] }
